name: Lars Lentz Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22398
title: Lars Lentz Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f4187'
    - '#171324'
    - '#a4404d'
    - '#cd7a70'
    - '#ccaeb7'
  brandStrength: 0.26720128464512527
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
