name: Lars Lentz Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14211
title: Lars Lentz Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16120e'
    - '#fcffdc'
    - '#f2a874'
    - '#974248'
    - '#7277ac'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
